### ISSUE TITLE
Question About Plugin Effectiveness 

### ISSUE THREAD

**Issue by johnnydevs** [zero-24/plg_system_httpheader#35]
This isn't an issue, so feel free to label accordingly.

Firstly thank you for developing this plugin it's very useful and easy to use! :)

I use a third party service to monitor and audit my Joomla sites, this service has flagged the headers as an issue which is why I will be installing your plugin. However there is a note about plugins not being good enough as they only run when PHP is invoked, and more work is required to ensure security.

The note is;

> Some Joomla Extensions/Plugins that allow you to add headers on responses will allow you to add this header HOWEVER THIS IS NOT GOOD ENOUGH as they only run when PHP is invoked. For the full protection this header has to be returned for EVERY REQUEST in a webspace, not just those that terminate through your index.php or php scripts. This is why our check looks at a 404 page, and not specifically your /index.php or homepage.

Does this mean that your plugin offers _some_ protection. but I would still need to configure security at the web server (e.g. htaccess)?

I had planned to benchmark the results and effectiveness of the plugin on https://securityheaders.com I assume it will improve the current score.

Thanks
J

**Comment by zero-24** [comment]
Hi,

the note you shared is partly right. Yes the headers only get added to your page when your page is called.

So when your page is loaded and Joomla sends the HTML to the browser this plugin is triggered and the headers are set.

Its right that in some cases this plugin is not triggered. For example when you upload an static html site and than load that directly.
Or when you upload an image an directly open that in the browser.

For example we have a core htaccess protection for svg files. When you call an uploaded svg files directly in the browser and not whin the context of joomla we do not have any control over it so such header has to be set on the htaccess level.

Can I ask what kind of monitor and audit service came with that suggestion?

In general yes using the htacces is a server level protection and applys to all content served from that server, and before Joomla runs.

This plugin can by design only add headers to pages that are served by joomla and not content thats outside of the site.

Its not directly less secure or more secure but a different place where you configure the headers for your Joomla site.

**Comment by zero-24** [comment]
> I had planned to benchmark the results and effectiveness of the plugin on https://securityheaders.com I assume it will improve the current score.

That page loads your joomla site and there you will see the headers set once configured in the plugin.

**Comment by zero-24** [comment]
In the end it boils down to something like this:

Your car key protects you against someone stealing your car. The car key cant protect you against someone stealing the flower that stands next to your car. A lock for the garage can protect you against someone stealing the car and the flower. But nothing inside the car can protect the flower that stands next to it.

I hope that helps to understand the topic. :-)

**Comment by johnnydevs** [comment]
Thanks for the explanation @zero-24 

My question is in no way supposed be be critical of the plugin, it's fantastic. I was just looking for clarification.

The third party site is mysites.guru (also a fantastic service, I am not affiliated with just seen the note and wanted clarification).

Many thanks and I look forward to any further developments you have planned!

**Comment by zero-24** [comment]
Great so this can be closed or do you have more questions? :-)

**Comment by johnnydevs** [comment]
Yes feel free to close, thanks again for the explanation and the great plugin :)
