### ISSUE TITLE
Improvement to be made

### ISSUE THREAD

**Issue by ghost** [zero-24/plg_system_httpheader#41]
I moved to Joomla4 recently. My observation was that many plugins are not CSP friendly. They write <script> in the body and also use inline event handler sparingly.

This httpheader plugin is great but still I encountered 2 issues before I can set the policy out of report-only:
1) It seems to me that this plugin generates "nonce" for scripts in the "head" only. <script> inside the "body" are not treated.
2) keyword {nonce} does not work in script-src-elem for "unknown reason".

I can workaround these issues by calculating the "sha265-" hashes myself and put the hashes in script-src for inline<script> in the body and 'unsafe-hashes' for inline event handler.

These workarounds work in Chrome and Edge but not Firefox.

Firefox does not support script-src-elem,  script-src-atr  nor 'unsafe-hashes' at all. The only way for the site to wok for Firefox, unless they change, is to put 'unsafe-inline' in the script-src. Any nonce  or hashes there in script-src will void the 'unsafe-inline'.

Ideally the setting that works for Chrome, Edge and Firefox with best XSS protection are:
script-src:  'self' 'unsafe-inline'
script-src-elem: 'self' {nonce} and my manual 'sha265-hashes'
script-src-atr:  my manual 'sha265-hashes' for inline event handler.

My requests are:
1) Make {nonce} work for script-src-elem. This is critical for a workable solution that works across main browsers.
2) Optionally if the plugin nonce can cover inline <script> in the body that can save one from sha256 hashes.

**Comment by zero-24** [comment]
> It seems to me that this plugin generates "nonce" for scripts in the "head" only. <script> inside the "body" are not treated.

Yes the plugin only catches the scripts and styles that are passed via the Joomla API everything thats echo'd directly into the template files or added to the site without using the Joomla API will intentionally not be catched by this plugin. The problem is when we would whitelist also that scripts we would whitelist also malicius scripts and the point of using an CSP is gone ;)

> keyword {nonce} does not work in script-src-elem for "unknown reason".

Are you sure you are using this plugin and not the core plugin? This plugin here does not support nonces alltogether as that also required a change within the Joomla Core which is only shipped with J4 and the respective core plugin.

When you are talking about the core plugin on a quick look we have to add the two directives to this option here: https://github.com/joomla/joomla-cms/blob/4.2-dev/plugins/system/httpheaders/httpheaders.php#L125-L128

Ps the keyword nonce will be optional for using nonces starting from 4.2.0

When its the core plugin please create an issue or PR here: https://github.com/joomla/joomla-cms and this here can be closed.

Thanks

**Comment by zero-24** [comment]
Closing as there has been an issue against the CMS created: https://github.com/joomla/joomla-cms/issues/38291#issue-1307483351
